import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Nav from './components/Nav'
import HomeHero from './components/HomeHero'
// import SideNav from './components/sideMenu'

export default function Home() {
  return (
    <div className={`${styles["app-home"]} bg-appGray`}>
      {/* <SideNav /> */}
      <Nav />
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className={styles.main}>
        <HomeHero />
        <div className="container mx-auto grid grid-cols-2 gap-4 gap-8 px-4 pt-10">
        <div className={styles["intro-section-left"]}>
            <div className={`${styles["intro-featured-img"]} inline-block`}>
              <Image src="/model1.jpeg" width={400} height={500} alt="model" />
            </div>
          </div>

          <div className={styles["intro-section-right"]}>
            <h1 className="app-title-1">Be Heard</h1>
            <div className="subtitle">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis facilis totam qui iste? Odio blanditiis eaque molestiae rem magnam nihil voluptas reiciendis, optio minus hic beatae doloremque quisquam cupiditate! Necessitatibus.
            </div>

            <div className="cta">
              <button className='border mt-10 hover:text-white'>Join A Room</button>
              {/* <Image src="/circle.jpeg" width={50} height={50} alt="circle" /> */}
            {/* <Image src="/circle.svg" alt="Vercel Logo" width={72} height={16} /> */}
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/whoismuktar"
          target="_blank"
          rel="noopener noreferrer"
        >
          Designed with ❤️ by whoIsMuktar
        </a>
      </footer>
    </div>
  )
}
